---
title: Style Guide
---

This guide serves as a reference for anyone authoring, editing, or reviewing the pro-product documentation.


::: {.callout-note appearance="simple" collapse="true"}

## Formatting Guide

The Doc Checklist & Formatting Style Guide is a separate guide providing:

- Syntax references
- Formatting references
- The documentation workflow 
- Documentation checklists for authoring and reviewing the documentation
:::

## Grammar

### Active/passive voice
	
- Avoid passive voice unless it is unavoidable.
- Use the active form of nouns (displays -not- displayed).    

Per the Microsoft Manual of Style:

- Active voice emphasizes the person or thing performing the action.
- It’s more direct than passive voice, which can be confusing or sound formal.

::: {.callout-tip}
Please review the [Posit Voice](/getting-started/getting-started.html#posit-voice) section for additional information.
:::

### Parentheses 

APA Style 6th Edition:

- Punctuation goes inside of parentheses when the entire sentence is enclosed in the parentheses.

- Punctuation goes outside of parentheses when only a portion of a sentence is enclosed in parentheses.

### Contractions

*Avoid*

### Quotation marks

Punctuation - (inside vs. outside):

- Inside quotation marks. Piece of code = outside. 
- Examples:     

    - grammar: “My friend Mary,” she said, “is crazy!”  
    - code: To start the program, run `runApp`.

### Oxford (serial) comma

- Include the final comma in a list of three or more items. The cat liked to jump, eat, and meow.

### Dashes

- En dash vs. Em dash:
    - En dash:  A dash the width of an “n”. Use for ranges or spans of numbers.
    - Em dash: A dash the width of an “m”. Can take the place of colons.

### i.e. vs. e.g.

- i.e.: In other words
- e.g.:  For example

### etc.

- When used in the middle of a sentence, and is not enclosed in parentheses, include a period and a comma after the abbreviation.
- If used at the end of a sentence, simply use a period.
- If enclosed in a parentheses and is at the end of the sentence, use a period. No comma is needed.

## Content

### Titles and headings

- Titles and H1s: Title Case
- All other headings: Sentence case

:::{.callout-tip appearance="simple" collapse="true"}

#### Steps as headings

Especially for docs.posit.co - proper:

- If you are going to use a heading to represent a step/procedure, then the name of the heading should include the word “Step”. 
- For example, an H2 representing a step/procedure would be written as, “Step 1: Install RStudio Connect”. 

This is extremely important from an Accessibility perspective, especially for those who may be using a screen reader to listen to our documentation.
:::

### Callouts

Callouts, sometimes referred to as "admonitions", are used to draw attention to content and/or information that doesn't fit into the normal flow of text.

:::{.callout-note}
Quarto and MkDocs Material offer different types of callouts. 

Items marked with an <bold>*</bold> are only available w/ MkDocs Material.


 - [Quarto's callout types](https://quarto.org/docs/authoring/callouts.html#callout-types)
 - [MkDocs Matieral callout types](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)

:::

| Callout type | Definition
|---|-------------------
example <bold>*</bold> | Used for steps/procedures.
important | If this information is ignored, it is unlikely that the user will be able to complete the task or make configuration changes in the future.
info <bold>*</bold> | Additional information, such as, “Our recommended installation instructions for R allow you to make multiple versions of R available.”
note | Information that helps the user, provides additional information, clarity, and may increase efficiency.
question <bold>*</bold> | Typically reserved for when a user may require help information, solutions, support, etc. For example, “If you require help information, run `$ bash ./rsc-installer.sh help<LICENSE-KEY>`.”
quote <bold>*</bold> | When you directly quote the works of others in your documentation.
success <bold>*</bold> | Indicates that the install and/or configuration is complete.
tip | Information that makes the user’s experience easier, may contain additional functionality that is not required for installation or configuration or has information that an advanced user may be interested in.
warning / caution | Warning: Explains dangers that may result in personal injury or death. <br>Caution: Explains hazards that could damage a product, including data loss.

### Reusing content

We have several options for conveinently reusing content across our documentation. This allows us to easily duplicate information, without needing to update it in several places. Common use cases for this would be version numbers, common callouts/warnings, etc.

#### Snippets / macros

*MkDocs Material, only*

You can include the contents of another file, into your current file, by using a snippet. If the included file is updated, the updates automatically update anywhere that the snippet has been used.

MkDocs Material has a [complete description and the notation of snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/).

Notation:

`--8<-- "filename.ext"`

#### Includes

*Quarto, only*

To include a file, add the {{< include >}} shortcode at the location in your document where you want it included:


A very important thing to understand about includes is that they are equivalent to copying and pasting the text from the included file into the main file. This means that relative references (links, images, etc.) inside the included file resolve based on the directory of the main file not the included file.

Notation:

`{{< include _content.qmd >}}`

Quarto has a [complete description and the notation of includes](https://quarto.org/docs/authoring/includes.html).

#### Cross references

*Quarto, only*


### Proper nouns and UI elements

- Are always capitalized. 
- However, always follow the same capitalization format that is displayed in the UI when referring to product screens directly.
    - For example, if a menu name isn't capitalized in the UI, write it exactly as it appears. If it is in all caps, use all caps when referencing it in the docs.


### Procedures/steps

Action → Result should always be part of the action step

Examples: 

- Click **OK**. A dialog displays.
- The configuration section allows you to configure your product. Deleting this file may result in a loss of data.

#### Procedure formatting definitions

The checklist and formatting style guide has examples of when to use this formatting here.

Formatting | Definition |
---|----------|
 **Bold** | The name of any button, panel, field, drop-down, etc.,  should be bolded.  |
 *Italics* |Use as a placeholder, for emphasis, or for mathematical constants and variables. |
 Quotes | Use quotes when instructing the user to type something specific. |

### Lists

#### Bulleted lists:

- Ending punctuation: Be consistent. For each item in a list, stick to using ending punctuation or don’t use it at all.
- If there are two items/steps or fewer, then use bullet points or nothing at all. 
- When giving a user multiple options, for example:

    - To install RStudio, do one of the following:
    
        - Manual installation
        - Guided installation

#### Numbered lists

- Use ending punctuation.
- Use when a procedure needs to be specifically referenced.
- Use to describe things that need to be done in a sequential order

Please see [Procedures/steps](#proceduressteps) for more information.

### Calls to code

Calls to R, Python code, shell commands, & other languages.

Denote calls with the accent grave (example: `runApp`). Use the accent marks/backticks wherever appropriate. Ensure that  the text within already written accent marks exactly matches the code,  since it may change  how code is run and result in errors.

If the documentation framework doesn’t support accent graves, use code blocks, inline code, or whatever the framework supports.

### Gerunds & Tech jargon

Avoid.

### Numbers

As a general rule, spell out single-digit numbers, and use numerals to represent double-digit numbers, e.g., one and. 10.

### Acronyms

- Spell out the first occurrence of an acronym per topic/page/file, followed by the acronym in parentheses. 
- You do not need to define common acronyms, such as IP.

Example:
- The Central Intelligence Agency (CIA) is a civilian foreign intelligence service of the federal government of the United States. The CIA has no law enforcement function.

### Images

