project:
  type: website

website:
  title: "Technical Writing at Posit"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Getting Started"
        file: getting-started/getting-started.qmd
  page-navigation: true      
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - text: Start here
            href: getting-started/getting-started.qmd
          - text: Authoring tools
            href: getting-started/authoring-tools.qmd
          - text: Approach
            href: getting-started/approach.qmd
          - text: Where should it live?
            href: getting-started/location.qmd
      - section: "Writing"
        contents:
          - text: "Style Guide"
            href: writing/style-guide.qmd
          - text: "Rules & Best Practices"
            href: writing/doc-rules.qmd  
      - section: "Onboarding"
        contents:
        - text: "Overview"
          href: guides/onboarding.qmd
        - section: GitHub
          contents:
          - text: "Clone a Repo"
            href: guides/onboarding/training/github/clone-repo.qmd
          - text: "Open a PR"
            href: guides/onboarding/training/github/first-pr.qmd
        - text: Philosophy  
          href: guides/onboarding/philosophy.qmd                
        - text: Testing Envs
          href: guides/onboarding/testing-envs.qmd
      - section: "Doc Requests"
        contents:
        - text: Workflow
          href: guides/doc-requests.qmd
        - text: Triage
          href: guides/triage.qmd
      - section: "References"
        contents:
            - text: POCs
              href: references/pocs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true